version: "3.9"

services:
  abeja-qwen7b-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: abeja-qwen7b-demo
    container_name: abeja-qwen7b-demo
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - .:/app/abeja-qwen7b-demo
    working_dir: /app/abeja-qwen7b-demo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command:
      - /app/.venv/bin/jupyter
      - lab
      - --notebook-dir=/app/abeja-qwen7b-demo
      - --ip=0.0.0.0
      - --port=8888
      - --NotebookApp.token=
      - --NotebookApp.password=
      - --no-browser
      - --allow-root
